### ISSUE TITLE
Missing brackets in Spark_Dqtaframes 

### ISSUE THREAD

**Issue by Nethaji-nethu** [Thomas-George-T/MoviesLens-Analytics-in-Spark-and-Scala#2]
There are closing brackets missing in scala files in prepare_movies_dat/*.scala
prepare_ratings_dat/*.scala

**Comment by Thomas-George-T** [comment]
Please could you be more specific. A code snippet would really help.

**Comment by Nethaji-nethu** [comment]
Hi, it's no big deal but a little typo
In

https://github.com/Thomas-George-T/Movies-Analytics-in-Spark-and-Scala/blob/0d30bc9e7bfb7b7fb7fed454c30c1a588ed56856/Spark_DataFrames/prepare_movies_dat/prepare_movies.scala

And

https://github.com/Thomas-George-T/Movies-Analytics-in-Spark-and-Scala/blob/0d30bc9e7bfb7b7fb7fed454c30c1a588ed56856/Spark_DataFrames/prepare_ratings_dat/prepare_ratings.scala

Where the number of simple paranthesis are miss numbered

Apologies If you feel it's filthy 😅
Thank you.

**Comment by Thomas-George-T** [comment]
Done.

Thank you for bringing it to my notice.

Appreciate it.
